/* Prompt site SPA — hash routing, no dependencies.
   Data source: content/manifest.json (generated by scripts/build-manifest.mjs). */

(() => {
  'use strict';

  const app = document.getElementById('app');
  const els = {
    search: document.getElementById('search'),
    tag: document.getElementById('filter-tag'),
    images: document.getElementById('filter-images'),
    sort: document.getElementById('sort'),
    lightbox: document.getElementById('lightbox'),
    lbImg: document.getElementById('lb-img'),
    lbCounter: document.getElementById('lb-counter'),
    lbDownload: document.getElementById('lb-download'),
    lbClose: document.getElementById('lb-close'),
    lbPrev: document.getElementById('lb-prev'),
    lbNext: document.getElementById('lb-next'),
  };

  let posts = [];
  let promptOfDay = null;
  let lightboxImages = [];
  let lightboxIndex = 0;

  /* ------------------------------------------------------------- helpers */

  const escapeHtml = (s) => String(s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');

  const formatDate = (iso) => {
    const d = new Date(iso + 'T00:00:00');
    if (isNaN(d)) return iso;
    return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
  };

  const imageUrl = (post, file) =>
    `content/${encodeURIComponent(post.id)}/${file.split('/').map(encodeURIComponent).join('/')}`;

  const isFin = (file) => /^fin/i.test(file);

  const REF_SECTIONS = [
    ['style-ref', 'Style refs'],
    ['img-ref', 'Image refs'],
    ['omni-ref', 'Omni refs'],
  ];

  /* Plain-text preview of markdown content for list cards. */
  const snippet = (md, len) => md
    .replace(/```[^\n]*\n?/g, '')
    .replace(/^#+\s*/gm, '')
    .replace(/^[-*\d.]+\s+/gm, '')
    .replace(/[*_`]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, len);

  /* Minimal markdown renderer: headings, lists, code fences, inline code,
     bold, italic, links, paragraphs. Everything is HTML-escaped first. */
  function renderMarkdown(md) {
    const lines = md.replace(/\r\n/g, '\n').split('\n');
    const out = [];
    let para = [];
    let list = null; // 'ul' | 'ol'
    let code = null; // array of code lines

    const inline = (text) => escapeHtml(text)
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/(^|\W)\*([^*\n]+)\*(?=\W|$)/g, '$1<em>$2</em>')
      .replace(/\[([^\]]+)\]\((https?:[^)\s]+)\)/g,
        '<a href="$2" target="_blank" rel="noopener">$1</a>');

    const flushPara = () => {
      if (para.length) { out.push(`<p>${inline(para.join(' '))}</p>`); para = []; }
    };
    const flushList = () => {
      if (list) { out.push(`</${list}>`); list = null; }
    };

    for (const raw of lines) {
      if (code !== null) {
        if (/^```/.test(raw)) {
          out.push(
            `<div class="codeblock"><pre>${escapeHtml(code.join('\n'))}</pre>` +
            `<button class="btn btn-sm copy-btn" data-copy>Copy</button></div>`
          );
          code = null;
        } else {
          code.push(raw);
        }
        continue;
      }

      const line = raw.trimEnd();

      if (/^```/.test(line)) { flushPara(); flushList(); code = []; continue; }

      const h = line.match(/^(#{1,3})\s+(.*)$/);
      if (h) {
        flushPara(); flushList();
        out.push(`<h${h[1].length + 1}>${inline(h[2])}</h${h[1].length + 1}>`);
        continue;
      }

      const ul = line.match(/^[-*]\s+(.*)$/);
      const ol = line.match(/^\d+\.\s+(.*)$/);
      if (ul || ol) {
        flushPara();
        const kind = ul ? 'ul' : 'ol';
        if (list !== kind) { flushList(); out.push(`<${kind}>`); list = kind; }
        out.push(`<li>${inline((ul || ol)[1])}</li>`);
        continue;
      }

      if (line === '') { flushPara(); flushList(); continue; }

      para.push(line);
    }

    if (code !== null) {
      out.push(
        `<div class="codeblock"><pre>${escapeHtml(code.join('\n'))}</pre>` +
        `<button class="btn btn-sm copy-btn" data-copy>Copy</button></div>`
      );
    }
    flushPara(); flushList();
    return out.join('\n');
  }

  /* Deterministic "random" pick per calendar day. */
  function pickPromptOfDay(prompts) {
    if (!Array.isArray(prompts) || prompts.length === 0) return null;
    const today = new Date();
    const key = `${today.getFullYear()}-${today.getMonth()}-${today.getDate()}`;
    let hash = 0;
    for (let i = 0; i < key.length; i++) hash = (hash * 31 + key.charCodeAt(i)) >>> 0;
    return prompts[hash % prompts.length];
  }

  /* --------------------------------------------------------------- state */

  function readHash() {
    const hash = location.hash.replace(/^#\/?/, '');
    const [path, query] = hash.split('?');
    const params = new URLSearchParams(query || '');
    if (path.startsWith('post/')) {
      return { view: 'post', id: decodeURIComponent(path.slice(5)) };
    }
    return {
      view: 'list',
      q: params.get('q') || '',
      tag: params.get('tag') || '',
      images: params.get('images') || '',
      sort: params.get('sort') || 'date-desc',
    };
  }

  function writeListHash() {
    const params = new URLSearchParams();
    if (els.search.value) params.set('q', els.search.value);
    if (els.tag.value) params.set('tag', els.tag.value);
    if (els.images.value) params.set('images', els.images.value);
    if (els.sort.value !== 'date-desc') params.set('sort', els.sort.value);
    const qs = params.toString();
    const next = qs ? `#/?${qs}` : '#/';
    if (location.hash !== next) history.replaceState(null, '', next);
    renderRoute();
  }

  /* ------------------------------------------------------------ filtering */

  function filteredPosts(state) {
    const q = state.q.trim().toLowerCase();
    let result = posts.filter((p) => {
      if (state.tag && !p.tags.includes(state.tag)) return false;
      if (state.images === 'with' && p.images.length === 0) return false;
      if (state.images === 'without' && p.images.length > 0) return false;
      if (q) {
        const haystack = `${p.title}\n${p.content}`.toLowerCase();
        if (!haystack.includes(q)) return false;
      }
      return true;
    });

    const cmp = {
      'date-desc': (a, b) => b.date.localeCompare(a.date) || a.title.localeCompare(b.title),
      'date-asc': (a, b) => a.date.localeCompare(b.date) || a.title.localeCompare(b.title),
      'title-asc': (a, b) => a.title.localeCompare(b.title),
      'title-desc': (a, b) => b.title.localeCompare(a.title),
    }[state.sort] || ((a, b) => 0);

    return result.sort(cmp);
  }

  /* ------------------------------------------------------------ rendering */

  function tagPill(tag, active) {
    return `<button class="tag${active ? ' active' : ''}" data-tag="${escapeHtml(tag)}">#${escapeHtml(tag)}</button>`;
  }

  function renderList(state) {
    const list = filteredPosts(state);
    const parts = [];

    if (promptOfDay) {
      parts.push(`
        <section class="potd">
          <div>
            <div class="potd-label">Midjourney Prompt of the Day</div>
            <div class="potd-text">${escapeHtml(promptOfDay.prompt)}</div>
          </div>
          <button class="btn" data-copy-text="${escapeHtml(promptOfDay.prompt)}">Copy</button>
        </section>`);
    }

    parts.push(`<div class="count">${list.length} post${list.length === 1 ? '' : 's'}</div>`);

    if (list.length === 0) {
      parts.push('<div class="status">No posts match the current filters.</div>');
    } else {
      const cards = list.map((p) => {
        const thumbs = p.images.length
          ? `<div class="post-thumbs-row">${p.images.slice(0, 7).map((img, i) =>
              `<img class="thumb${isFin(img) ? ' thumb-fin' : ''}" loading="lazy" src="${imageUrl(p, img)}" alt="${escapeHtml(p.title)} image ${i + 1}">`
            ).join('')}</div>`
          : '<div class="thumb-empty">text</div>';
        return `
          <article class="post-card" data-post="${escapeHtml(p.id)}" tabindex="0" role="link" aria-label="${escapeHtml(p.title)}">
            <div class="post-thumbs">${thumbs}</div>
            <div class="post-meta">
              <div class="post-title">${escapeHtml(p.title)}</div>
              <div class="post-snippet">${escapeHtml(snippet(p.content, 220))}</div>
              <div class="post-tags">${p.tags.map((t) => tagPill(t, t === state.tag)).join('')}</div>
              <div class="post-date">${formatDate(p.date)}</div>
            </div>
          </article>`;
      });
      parts.push(`<div class="post-list">${cards.join('')}</div>`);
    }

    app.innerHTML = parts.join('\n');
  }

  function renderPost(id) {
    const p = posts.find((x) => x.id === id);
    if (!p) {
      app.innerHTML = `
        <a class="back-link" href="#/">&#8592; Back to all posts</a>
        <div class="status">Post not found.</div>`;
      return;
    }

    // One flat lightbox list: finals first, then each ref section in order.
    const gallery = p.images.map((img) => img);
    const figure = (file, alt, i, extra) => `
      <figure class="post-image-item${extra || ''}">
        <img loading="lazy" src="${imageUrl(p, file)}" alt="${escapeHtml(alt)}" data-lightbox="${i}">
        <a class="btn btn-sm" href="${imageUrl(p, file)}" download>Download</a>
      </figure>`;

    const images = p.images.length
      ? `<div class="post-images">${p.images.map((img, i) =>
          figure(img, `${p.title} image ${i + 1}`, i, isFin(img) ? ' fin' : '')
        ).join('')}</div>`
      : '';

    let refSections = '';
    for (const [dir, label] of REF_SECTIONS) {
      const files = p.refs?.[dir];
      if (!files?.length) continue;
      refSections += `
        <section class="ref-section">
          <div class="ref-label">${label}</div>
          <div class="post-images post-images-refs">${files.map((f, j) => {
            const i = gallery.length;
            gallery.push(`${dir}/${f}`);
            return figure(`${dir}/${f}`, `${p.title} ${label.toLowerCase()} ${j + 1}`, i);
          }).join('')}</div>
        </section>`;
    }

    app.innerHTML = `
      <div class="post-view">
        <a class="back-link" href="#/">&#8592; Back to all posts</a>
        <h1 class="post-title">${escapeHtml(p.title)}</h1>
        <div class="post-tags">${p.tags.map((t) => tagPill(t, false)).join('')}</div>
        <div class="post-date">${formatDate(p.date)}</div>
        ${images}
        ${refSections}
        <div class="post-content">${renderMarkdown(p.content)}</div>
      </div>`;

    lightboxImages = gallery.map((img) => imageUrl(p, img));
    document.title = `${p.title} — GARDEN`;
  }

  function renderRoute() {
    const state = readHash();
    closeLightbox();
    if (state.view === 'post') {
      renderPost(state.id);
    } else {
      els.search.value = state.q;
      els.tag.value = state.tag;
      els.images.value = state.images;
      els.sort.value = state.sort;
      document.title = 'GARDEN';
      renderList(state);
    }
    window.scrollTo(0, 0);
  }

  /* ------------------------------------------------------------- lightbox */

  function openLightbox(index) {
    if (!lightboxImages.length) return;
    lightboxIndex = index;
    updateLightbox();
    els.lightbox.hidden = false;
    document.body.style.overflow = 'hidden';
  }

  function updateLightbox() {
    const src = lightboxImages[lightboxIndex];
    els.lbImg.src = src;
    els.lbDownload.href = src;
    els.lbCounter.textContent = `${lightboxIndex + 1} / ${lightboxImages.length}`;
    els.lbPrev.disabled = lightboxIndex === 0;
    els.lbNext.disabled = lightboxIndex === lightboxImages.length - 1;
  }

  function closeLightbox() {
    if (els.lightbox.hidden) return;
    els.lightbox.hidden = true;
    els.lbImg.src = '';
    document.body.style.overflow = '';
  }

  /* --------------------------------------------------------------- events */

  els.search.addEventListener('input', writeListHash);
  els.tag.addEventListener('change', writeListHash);
  els.images.addEventListener('change', writeListHash);
  els.sort.addEventListener('change', writeListHash);

  window.addEventListener('hashchange', renderRoute);

  app.addEventListener('click', (e) => {
    const copyText = e.target.closest('[data-copy-text]');
    if (copyText) {
      navigator.clipboard.writeText(copyText.getAttribute('data-copy-text'));
      copyText.textContent = 'Copied';
      setTimeout(() => { copyText.textContent = 'Copy'; }, 1500);
      return;
    }
    const copyBlock = e.target.closest('[data-copy]');
    if (copyBlock) {
      navigator.clipboard.writeText(copyBlock.parentElement.querySelector('pre').textContent);
      copyBlock.textContent = 'Copied';
      setTimeout(() => { copyBlock.textContent = 'Copy'; }, 1500);
      return;
    }
    const tag = e.target.closest('[data-tag]');
    if (tag) {
      e.stopPropagation();
      els.tag.value = tag.getAttribute('data-tag');
      location.hash = '#/';
      writeListHash();
      return;
    }
    const lbImg = e.target.closest('[data-lightbox]');
    if (lbImg) {
      openLightbox(Number(lbImg.getAttribute('data-lightbox')));
      return;
    }
    const card = e.target.closest('[data-post]');
    if (card && !e.target.closest('a')) {
      location.hash = `#/post/${encodeURIComponent(card.getAttribute('data-post'))}`;
    }
  });

  app.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') {
      const card = e.target.closest('[data-post]');
      if (card) location.hash = `#/post/${encodeURIComponent(card.getAttribute('data-post'))}`;
    }
  });

  els.lbClose.addEventListener('click', closeLightbox);
  els.lbPrev.addEventListener('click', () => { if (lightboxIndex > 0) { lightboxIndex--; updateLightbox(); } });
  els.lbNext.addEventListener('click', () => { if (lightboxIndex < lightboxImages.length - 1) { lightboxIndex++; updateLightbox(); } });
  els.lightbox.addEventListener('click', (e) => { if (e.target === els.lightbox) closeLightbox(); });

  document.addEventListener('keydown', (e) => {
    if (els.lightbox.hidden) return;
    if (e.key === 'Escape') closeLightbox();
    if (e.key === 'ArrowLeft' && lightboxIndex > 0) { lightboxIndex--; updateLightbox(); }
    if (e.key === 'ArrowRight' && lightboxIndex < lightboxImages.length - 1) { lightboxIndex++; updateLightbox(); }
  });

  /* ----------------------------------------------------------------- init */

  async function init() {
    try {
      const [manifestRes, potdRes] = await Promise.all([
        fetch('content/manifest.json'),
        fetch('content/prompt-of-day.json'),
      ]);
      if (!manifestRes.ok) throw new Error(`manifest.json: HTTP ${manifestRes.status}`);
      const manifest = await manifestRes.json();
      posts = manifest.posts || [];

      if (potdRes.ok) {
        const potd = await potdRes.json();
        promptOfDay = pickPromptOfDay(potd.prompts || potd);
      }

      const tags = [...new Set(posts.flatMap((p) => p.tags))].sort();
      for (const t of tags) {
        const opt = document.createElement('option');
        opt.value = t;
        opt.textContent = `#${t}`;
        els.tag.appendChild(opt);
      }

      renderRoute();
    } catch (err) {
      app.innerHTML = `<div class="status">Failed to load content: ${escapeHtml(err.message)}.<br>
        Run <code>npm run build</code> to generate <code>content/manifest.json</code>.</div>`;
    }
  }

  init();
})();
