/* Prompt site SPA — hash routing, no dependencies.
   Data source: content/manifest.json (generated by scripts/build-manifest.mjs). */

(() => {
  'use strict';

  const app = document.getElementById('app');
  const els = {
    search: document.getElementById('search'),
    tag: document.getElementById('filter-tag'),
    images: document.getElementById('filter-images'),
    sort: document.getElementById('sort'),
    treeModal: document.getElementById('tree-modal'),
    treeBody: document.getElementById('tree-body'),
    treeClose: document.getElementById('tree-close'),
    lightbox: document.getElementById('lightbox'),
    lbImg: document.getElementById('lb-img'),
    lbCounter: document.getElementById('lb-counter'),
    lbDownload: document.getElementById('lb-download'),
    lbClose: document.getElementById('lb-close'),
    lbPrev: document.getElementById('lb-prev'),
    lbNext: document.getElementById('lb-next'),
  };

  let posts = [];
  let assets = [];
  let assetDims = {};
  let promptOfDay = null;
  let lightboxImages = [];
  let lightboxIndex = 0;
  let zipTargets = []; // [{path, name}] for the current view's "download all"
  let zipName = 'images.zip';

  /* ------------------------------------------------------------- helpers */

  const escapeHtml = (s) => String(s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');

  const formatDate = (iso) => {
    const d = new Date(iso + 'T00:00:00');
    if (isNaN(d)) return iso;
    return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
  };

  const imageUrl = (post, file) =>
    `content/${encodeURIComponent(post.id)}/${file.split('/').map(encodeURIComponent).join('/')}`;

  const isFin = (file) => /^fin/i.test(file);

  const REF_SECTIONS = [
    ['style-ref', 'Style refs'],
    ['img-ref', 'Image refs'],
    ['omni-ref', 'Omni refs'],
  ];

  const getSourceLabel = (postId) => {
    const tpostId = postId.toLowerCase();
    return tpostId.startsWith('gpt-') ? 'GPT' : tpostId.startsWith('mj-') ? 'MJ' : tpostId.startsWith('gem-') ? 'GEM' : '';
  };

  const authorLink = (handle) =>
    `<a class="author-link" href="https://x.com/${encodeURIComponent(handle)}" target="_blank" rel="noopener">@${escapeHtml(handle)}</a>`;

  const getLayout = () => {
    try {
      const v = localStorage.getItem('garden-layout');
      return v === 'grid' || v === 'masonry' ? v : 'list';
    } catch { return 'list'; }
  };

  /* width/height attributes from build-time dims — the browser reserves the
     image's aspect ratio before it loads, preventing layout shift. */
  const dimAttrs = (dims, key) => {
    const d = dims && dims[key];
    return d ? ` width="${d[0]}" height="${d[1]}"` : '';
  };

  /* Newest-first order used for prev/next cycling in the post view. */
  const postOrder = () =>
    [...posts].sort((a, b) => b.date.localeCompare(a.date) || a.title.localeCompare(b.title));

  /* Plain-text preview of markdown content for list cards. */
  const snippet = (md, len) => md
    .replace(/```[^\n]*\n?/g, '')
    .replace(/^#+\s*/gm, '')
    .replace(/^[-*\d.]+\s+/gm, '')
    .replace(/[*_`]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, len);

  /* Minimal markdown renderer: headings, lists, code fences, inline code,
     bold, italic, links, paragraphs. Everything is HTML-escaped first. */
  function renderMarkdown(md) {
    const lines = md.replace(/\r\n/g, '\n').split('\n');
    const out = [];
    let para = [];
    let list = null; // 'ul' | 'ol'
    let code = null; // array of code lines

    const inline = (text) => escapeHtml(text)
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/(^|\W)\*([^*\n]+)\*(?=\W|$)/g, '$1<em>$2</em>')
      .replace(/\[([^\]]+)\]\((https?:[^)\s]+)\)/g,
        '<a href="$2" target="_blank" rel="noopener">$1</a>');

    const flushPara = () => {
      if (para.length) { out.push(`<p>${inline(para.join(' '))}</p>`); para = []; }
    };
    const flushList = () => {
      if (list) { out.push(`</${list}>`); list = null; }
    };

    for (const raw of lines) {
      if (code !== null) {
        if (/^```/.test(raw)) {
          out.push(
            `<div class="codeblock"><pre>${escapeHtml(code.join('\n'))}</pre>` +
            `<button class="btn btn-sm copy-btn" data-copy>Copy</button></div>`
          );
          code = null;
        } else {
          code.push(raw);
        }
        continue;
      }

      const line = raw.trimEnd();

      if (/^```/.test(line)) { flushPara(); flushList(); code = []; continue; }

      const h = line.match(/^(#{1,3})\s+(.*)$/);
      if (h) {
        flushPara(); flushList();
        out.push(`<h${h[1].length + 1}>${inline(h[2])}</h${h[1].length + 1}>`);
        continue;
      }

      const ul = line.match(/^[-*]\s+(.*)$/);
      const ol = line.match(/^\d+\.\s+(.*)$/);
      if (ul || ol) {
        flushPara();
        const kind = ul ? 'ul' : 'ol';
        if (list !== kind) { flushList(); out.push(`<${kind}>`); list = kind; }
        out.push(`<li>${inline((ul || ol)[1])}</li>`);
        continue;
      }

      if (line === '') { flushPara(); flushList(); continue; }

      para.push(line);
    }

    if (code !== null) {
      out.push(
        `<div class="codeblock"><pre>${escapeHtml(code.join('\n'))}</pre>` +
        `<button class="btn btn-sm copy-btn" data-copy>Copy</button></div>`
      );
    }
    flushPara(); flushList();
    return out.join('\n');
  }

  /* ------------------------------------------------- zip (STORE, no deps) */

  const crcTable = (() => {
    const t = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
      let c = n;
      for (let k = 0; k < 8; k++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1;
      t[n] = c;
    }
    return t;
  })();

  function crc32(bytes) {
    let c = 0xFFFFFFFF;
    for (let i = 0; i < bytes.length; i++) c = crcTable[(c ^ bytes[i]) & 0xFF] ^ (c >>> 8);
    return (c ^ 0xFFFFFFFF) >>> 0;
  }

  /* Build an uncompressed .zip (images are already compressed WebP). */
  function buildZip(entries) { // entries: [{name, bytes: Uint8Array}]
    const encoder = new TextEncoder();
    const chunks = [];
    const central = [];
    let offset = 0;

    const now = new Date();
    const dosTime = (now.getHours() << 11) | (now.getMinutes() << 5) | (now.getSeconds() >> 1);
    const dosDate = ((now.getFullYear() - 1980) << 9) | ((now.getMonth() + 1) << 5) | now.getDate();

    for (const { name, bytes } of entries) {
      const nameBytes = encoder.encode(name);
      const crc = crc32(bytes);
      const header = new DataView(new ArrayBuffer(30));
      header.setUint32(0, 0x04034b50, true);
      header.setUint16(4, 20, true);          // version needed
      header.setUint16(6, 0x0800, true);      // UTF-8 names
      header.setUint16(8, 0, true);           // method: store
      header.setUint16(10, dosTime, true);
      header.setUint16(12, dosDate, true);
      header.setUint32(14, crc, true);
      header.setUint32(18, bytes.length, true);
      header.setUint32(22, bytes.length, true);
      header.setUint16(26, nameBytes.length, true);
      header.setUint16(28, 0, true);
      chunks.push(new Uint8Array(header.buffer), nameBytes, bytes);
      central.push({ nameBytes, crc, size: bytes.length, offset });
      offset += 30 + nameBytes.length + bytes.length;
    }

    let cdSize = 0;
    for (const e of central) {
      const cd = new DataView(new ArrayBuffer(46));
      cd.setUint32(0, 0x02014b50, true);
      cd.setUint16(4, 20, true);
      cd.setUint16(6, 20, true);
      cd.setUint16(8, 0x0800, true);
      cd.setUint16(10, 0, true);
      cd.setUint16(12, dosTime, true);
      cd.setUint16(14, dosDate, true);
      cd.setUint32(16, e.crc, true);
      cd.setUint32(20, e.size, true);
      cd.setUint32(24, e.size, true);
      cd.setUint16(28, e.nameBytes.length, true);
      cd.setUint32(42, e.offset, true);
      chunks.push(new Uint8Array(cd.buffer), e.nameBytes);
      cdSize += 46 + e.nameBytes.length;
    }

    const end = new DataView(new ArrayBuffer(22));
    end.setUint32(0, 0x06054b50, true);
    end.setUint16(8, central.length, true);
    end.setUint16(10, central.length, true);
    end.setUint32(12, cdSize, true);
    end.setUint32(16, offset, true);
    chunks.push(new Uint8Array(end.buffer));

    return new Blob(chunks, { type: 'application/zip' });
  }

  async function downloadAllZip(button) {
    if (!zipTargets.length || button.disabled) return;
    const original = button.textContent;
    button.disabled = true;
    try {
      const entries = [];
      for (let i = 0; i < zipTargets.length; i++) {
        button.textContent = `Zipping ${i + 1}/${zipTargets.length}…`;
        const res = await fetch(zipTargets[i].path);
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        entries.push({ name: zipTargets[i].name, bytes: new Uint8Array(await res.arrayBuffer()) });
      }
      const url = URL.createObjectURL(buildZip(entries));
      const a = document.createElement('a');
      a.href = url;
      a.download = zipName;
      a.click();
      setTimeout(() => URL.revokeObjectURL(url), 10000);
      button.textContent = original;
    } catch (err) {
      button.textContent = 'Failed — retry?';
      setTimeout(() => { button.textContent = original; }, 2000);
    }
    button.disabled = false;
  }

  /* Copy an image to the clipboard (converted to PNG, the only format
     browsers accept). Falls back to copying the image URL as text. */
  async function copyImage(src, button) {
    const original = 'Copy';
    try {
      const res = await fetch(src);
      const bitmap = await createImageBitmap(await res.blob());
      const canvas = document.createElement('canvas');
      canvas.width = bitmap.width;
      canvas.height = bitmap.height;
      canvas.getContext('2d').drawImage(bitmap, 0, 0);
      const png = await new Promise((resolve) => canvas.toBlob(resolve, 'image/png'));
      await navigator.clipboard.write([new ClipboardItem({ 'image/png': png })]);
      button.textContent = 'Copied';
    } catch {
      try {
        await navigator.clipboard.writeText(new URL(src, location.href).href);
        button.textContent = 'Copied URL';
      } catch {
        button.textContent = 'Failed';
      }
    }
    setTimeout(() => { button.textContent = original; }, 1500);
  }

  /* Deterministic "random" pick per calendar day. */
  function pickPromptOfDay(prompts) {
    if (!Array.isArray(prompts) || prompts.length === 0) return null;
    const today = new Date();
    const key = `${today.getFullYear()}-${today.getMonth()}-${today.getDate()}`;
    let hash = 0;
    for (let i = 0; i < key.length; i++) hash = (hash * 31 + key.charCodeAt(i)) >>> 0;
    return prompts[hash % prompts.length];
  }

  /* --------------------------------------------------------------- state */

  function readHash() {
    const hash = location.hash.replace(/^#\/?/, '');
    const [path, query] = hash.split('?');
    const params = new URLSearchParams(query || '');
    if (path.startsWith('post/')) {
      return { view: 'post', id: decodeURIComponent(path.slice(5)) };
    }
    if (path === 'assets') return { view: 'assets' };
    if (path === 'privacy') return { view: 'privacy' };
    if (path !== '') return { view: '404' };
    return {
      view: 'list',
      q: params.get('q') || '',
      tag: params.get('tag') || '',
      images: params.get('images') || '',
      sort: params.get('sort') || 'date-desc',
    };
  }

  function writeListHash() {
    const params = new URLSearchParams();
    if (els.search.value) params.set('q', els.search.value);
    if (els.tag.value) params.set('tag', els.tag.value);
    if (els.images.value) params.set('images', els.images.value);
    if (els.sort.value !== 'date-desc') params.set('sort', els.sort.value);
    const qs = params.toString();
    const next = qs ? `#/?${qs}` : '#/';
    if (location.hash !== next) history.replaceState(null, '', next);
    renderRoute();
  }

  /* ------------------------------------------------------------ filtering */

  function filteredPosts(state) {
    const q = state.q.trim().toLowerCase();
    let result = posts.filter((p) => {
      if (state.tag && !p.tags.includes(state.tag)) return false;
      if (state.images === 'with' && p.images.length === 0) return false;
      if (state.images === 'without' && p.images.length > 0) return false;
      if (q) {
        const haystack = `${p.title}\n${p.content}`.toLowerCase();
        if (!haystack.includes(q)) return false;
      }
      return true;
    });

    const cmp = {
      'date-desc': (a, b) => b.date.localeCompare(a.date) || a.title.localeCompare(b.title),
      'date-asc': (a, b) => a.date.localeCompare(b.date) || a.title.localeCompare(b.title),
      'title-asc': (a, b) => a.title.localeCompare(b.title),
      'title-desc': (a, b) => b.title.localeCompare(a.title),
    }[state.sort] || ((a, b) => 0);

    return result.sort(cmp);
  }

  /* ------------------------------------------------------------ rendering */

  function tagPill(tag, active) {
    return `<button class="tag${active ? ' active' : ''}" data-tag="${escapeHtml(tag)}">#${escapeHtml(tag)}</button>`;
  }

  function renderList(state) {
    const list = filteredPosts(state);
    const parts = [];

    if (promptOfDay) {
      parts.push(`
        <section class="potd">
          <div>
            <div class="potd-label">Midjourney Prompt of the Day</div>
            <div class="potd-text">${escapeHtml(promptOfDay.prompt)}</div>
          </div>
          <button class="btn" data-copy-text="${escapeHtml(promptOfDay.prompt)}">Copy</button>
        </section>`);
    }

    const layout = getLayout();
    parts.push(`
      <div class="list-tools">
        <div class="count">${list.length} post${list.length === 1 ? '' : 's'}</div>
        <div class="list-actions">
          <button class="btn btn-sm" data-tree>Content tree</button>
          <div class="layout-toggle" role="group" aria-label="Layout">
            <button class="btn btn-sm${layout === 'list' ? ' active' : ''}" data-layout="list">List</button>
            <button class="btn btn-sm${layout === 'grid' ? ' active' : ''}" data-layout="grid">Grid</button>
            <button class="btn btn-sm${layout === 'masonry' ? ' active' : ''}" data-layout="masonry">Masonry</button>
          </div>
        </div>
      </div>`);

    if (list.length === 0) {
      parts.push('<div class="status">No posts match the current filters.</div>');
    } else if (layout === 'masonry') {
      const items = list.map((p) => {
        const tags = `<div class="masonry-tags">${p.tags.map((t) => tagPill(t, t === state.tag)).join('')}</div>`;
        if (!p.images.length) {
          return `
            <div class="masonry-item post-masonry-text" data-post="${escapeHtml(p.id)}" tabindex="0" role="link" aria-label="${escapeHtml(p.title)}">
              <div class="post-title">${escapeHtml(p.title)}</div>
              ${tags}
            </div>`;
        }
        return `
          <figure class="masonry-item post-masonry-item${isFin(p.images[0]) ? ' fin' : ''}" data-post="${escapeHtml(p.id)}" tabindex="0" role="link" aria-label="${escapeHtml(p.title)}">
            <img loading="lazy" src="${imageUrl(p, p.images[0])}" alt="${escapeHtml(p.title)}"${dimAttrs(p.dims, p.images[0])}>
            ${tags}
          </figure>`;
      });
      parts.push(`<div class="masonry post-masonry">${items.join('')}</div>`);
    } else if (layout === 'grid') {
      const cards = list.map((p) => {
        const heroPos = /^\d{1,3}% \d{1,3}%$/.test(p.hero || '')
          ? ` style="object-position:${p.hero}"` : '';
        const hero = p.images.length
          ? `<div class="post-hero${isFin(p.images[0]) ? ' fin' : ''}">
               <img loading="lazy" src="${imageUrl(p, p.images[0])}" alt="${escapeHtml(p.title)}"${heroPos}>
             </div>`
          : '<div class="post-hero empty">text-only</div>';

        return `
          <article class="post-card post-card-grid" data-post="${escapeHtml(p.id)}" data-source="${getSourceLabel(escapeHtml(p.id))}" tabindex="0" role="link" aria-label="${escapeHtml(p.title)}">
            ${hero}
            <div class="post-meta">
              <div class="post-title">${escapeHtml(p.title)}</div>
              <div class="post-tags">${p.tags.map((t) => tagPill(t, t === state.tag)).join('')}</div>
            </div>
          </article>`;
      });
      parts.push(`<div class="post-list grid">${cards.join('')}</div>`);
    } else {
      const cards = list.map((p) => {
        // hero crop anchor from hero.md; re-validated here since it lands in
        // a style attribute
        const heroPos = /^\d{1,3}% \d{1,3}%$/.test(p.hero || '')
          ? ` style="object-position:${p.hero}"` : '';
        const hero = p.images.length
          ? `<div class="post-hero${isFin(p.images[0]) ? ' fin' : ''}">
               <img loading="lazy" src="${imageUrl(p, p.images[0])}" alt="${escapeHtml(p.title)}"${heroPos}>
             </div>`
          : '<div class="post-hero empty">text-only</div>';

        return `
          <article class="post-card" data-post="${escapeHtml(p.id)}" data-source="${getSourceLabel(escapeHtml(p.id))}" tabindex="0" role="link" aria-label="${escapeHtml(p.title)}">
            ${hero}
            <div class="post-meta">
              <div class="post-title">${escapeHtml(p.title)}</div>
              <div class="post-snippet">${escapeHtml(snippet(p.content, 220))}</div>
              <div class="post-tags">${p.tags.map((t) => tagPill(t, t === state.tag)).join('')}</div>
              <div class="post-foot">
                <div class="post-date">${formatDate(p.date)}</div>
                ${p.author ? authorLink(p.author) : ''}
              </div>
            </div>
          </article>`;
      });
      parts.push(`<div class="post-list">${cards.join('')}</div>`);
    }

    app.innerHTML = parts.join('\n');
  }

  function renderPost(id) {
    const p = posts.find((x) => x.id === id);
    if (!p) {
      app.innerHTML = `
        <a class="back-link" href="#/">&#8592; Back to all posts</a>
        <div class="status">Post not found.</div>`;
      return;
    }

    // One flat lightbox list: finals first, then each ref section in order.
    // p.images is fin-first, so fin figures occupy the leading indices.
    const gallery = p.images.map((img) => img);
    const figure = (file, alt, i, extra, caption, styleAttr, imgStyle) => `
      <figure class="post-image-item${extra || ''}"${styleAttr || ''}>
        ${caption ? `<figcaption class="ref-label">${caption}</figcaption>` : ''}
        <img loading="lazy" src="${imageUrl(p, file)}" alt="${escapeHtml(alt)}" data-lightbox="${i}"${dimAttrs(p.dims, file)}${imgStyle || ''}>
        <div class="img-actions">
          <a class="btn btn-sm" href="${imageUrl(p, file)}" download>Download</a>
          <button class="btn btn-sm" data-copy-img="${imageUrl(p, file)}">Copy</button>
        </div>
      </figure>`;

    const finFiles = p.images.filter(isFin);
    const restFiles = p.images.filter((f) => !isFin(f));

    // The fin final gets its own row, captioned as the result. Its width is
    // sized so the image never exceeds 550px tall — computed here from the
    // build-time dimensions, so the space is exact before the image loads.
    const finRow = finFiles.map((img, i) => {
      const d = p.dims?.[img];
      const figStyle = d
        ? ` style="width:min(700px, 50vw, ${Math.round(550 * d[0] / d[1])}px)"`
        : '';
      // explicit ratio reserves the box before the image loads
      const imgStyle = d ? ` style="aspect-ratio:${d[0]}/${d[1]}"` : '';
      return figure(img, `${p.title} image ${i + 1}`, i, ' fin fin-hero', 'Result', figStyle, imgStyle);
    }).join('');
    const images = restFiles.length
      ? `<div class="post-images">${restFiles.map((img, j) =>
        figure(img, `${p.title} image ${finFiles.length + j + 1}`, finFiles.length + j)
      ).join('')}</div>`
      : '';

    let refSections = '';
    for (const [dir, label] of REF_SECTIONS) {
      const files = p.refs?.[dir];
      if (!files?.length) continue;
      refSections += `
        <section class="ref-section">
          <div class="ref-label">${label}</div>
          <div class="post-images post-images-refs">${files.map((f, j) => {
        const i = gallery.length;
        gallery.push(`${dir}/${f}`);
        return figure(`${dir}/${f}`, `${p.title} ${label.toLowerCase()} ${j + 1}`, i);
      }).join('')}</div>
        </section>`;
    }

    // Zip bundles the images the final was created from: non-fin post
    // images plus refs, never the fin final itself.
    const zipFiles = [...restFiles, ...gallery.slice(p.images.length)];
    zipTargets = zipFiles.map((img) => ({ path: imageUrl(p, img), name: img }));
    zipName = `${p.id}.zip`;

    const order = postOrder();
    const idx = order.findIndex((x) => x.id === p.id);
    const prev = idx > 0 ? order[idx - 1] : null;
    const next = idx < order.length - 1 ? order[idx + 1] : null;
    const navBtn = (target, label) => target
      ? `<a class="btn btn-sm" href="#/post/${encodeURIComponent(target.id)}" aria-label="${label} post">${label === 'Previous' ? '&#8592; Prev' : 'Next &#8594;'}</a>`
      : `<button class="btn btn-sm" disabled>${label === 'Previous' ? '&#8592; Prev' : 'Next &#8594;'}</button>`;

    app.innerHTML = `
      <div class="post-view">
        <div class="post-topnav">
          <a class="back-link" href="#/">&#8592; Back to all posts</a>
          <div class="post-cycle">
            ${navBtn(prev, 'Previous')}
            <span class="post-cycle-count">${idx + 1} / ${order.length}</span>
            ${navBtn(next, 'Next')}
          </div>
        </div>
        <h1 class="post-title">${escapeHtml(p.title)}</h1>
        <div class="post-tags">
          ${p.tags.map((t) => tagPill(t, false)).join('')}
          ${p.author ? `<span class="post-author"><span class="author-label">Author</span>${authorLink(p.author)}</span>` : ''}
        </div>
        <div class="post-date">${formatDate(p.date)}</div>
        ${finRow}
        <div class="post-content post-content-prompt">${renderMarkdown(p.content)}</div>
        ${zipTargets.length >= 2 ? '<button class="btn btn-sm post-zip" data-zip>Download reference zip</button>' : ''}
        ${images}
        ${refSections}
      </div>`;

    lightboxImages = gallery.map((img) => imageUrl(p, img));
    document.title = `${p.title} — GARDEN`;
  }

  function renderAssets() {
    zipTargets = assets.map((f) => ({ path: `data/${encodeURIComponent(f)}`, name: f }));
    zipName = 'garden-assets.zip';
    lightboxImages = assets.map((f) => `data/${encodeURIComponent(f)}`);

    const items = assets.map((f, i) => `
      <figure class="masonry-item${isFin(f) ? ' fin' : ''}">
        <img loading="lazy" src="data/${encodeURIComponent(f)}" alt="Asset ${escapeHtml(f)}" data-lightbox="${i}"${dimAttrs(assetDims, f)}>
        <a class="btn btn-sm" href="data/${encodeURIComponent(f)}" download>Download</a>
      </figure>`).join('');

    app.innerHTML = `
      <div class="assets-head">
        <div class="count">${assets.length} asset${assets.length === 1 ? '' : 's'}</div>
        ${assets.length ? '<button class="btn" data-zip>Download all (.zip)</button>' : ''}
      </div>
      ${assets.length
        ? `<div class="masonry">${items}</div>`
        : '<div class="status">No assets yet. Drop images into the data/ folder and run <code>npm run build</code>.</div>'}`;

    document.title = 'Assets — GARDEN';
  }

  function renderPrivacy() {
    app.innerHTML = `
      <div class="post-view page-view">
        <a class="back-link" href="#/">&#8592; Back to all posts</a>
        <h1 class="post-title">Privacy</h1>
        <div class="post-content">
          <p>GARDEN is a static site. It sets no cookies, runs no analytics or
          tracking scripts, and has no accounts, forms, or comment systems.
          Nothing you do here is collected or stored by this site.</p>
          <h2>Hosting</h2>
          <p>The site is hosted on GitHub Pages. GitHub may log basic technical
          information about visits (such as IP addresses) for security and
          operational purposes, as described in the
          <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" target="_blank" rel="noopener">GitHub Privacy Statement</a>.</p>
          <h2>Downloads and clipboard</h2>
          <p>Image downloads, zip bundling, and copy-to-clipboard all happen
          entirely in your browser. Nothing is uploaded anywhere.</p>
          <h2>External links</h2>
          <p>Links to X and GitHub lead to third-party sites governed by their
          own privacy policies.</p>
          <h2>Contact</h2>
          <p>Questions? Open an issue on the
          <a href="https://github.com/egoprry/prompt-site" target="_blank" rel="noopener">GitHub repository</a>.</p>
        </div>
      </div>`;
    document.title = 'Privacy — GARDEN';
  }

  function render404() {
    app.innerHTML = `
      <div class="notfound">
        <div class="notfound-code">404</div>
        <p class="notfound-text">This page doesn't exist.</p>
        <a class="btn" href="#/">Back to GARDEN</a>
      </div>`;
    document.title = '404 — GARDEN';
  }

  function renderRoute() {
    const state = readHash();
    closeLightbox();
    closeTree();
    const navFor = state.view === 'assets' ? 'assets'
      : (state.view === 'list' || state.view === 'post') ? 'list' : '';
    document.querySelectorAll('.nav-link').forEach((a) => {
      a.classList.toggle('active', a.getAttribute('data-nav') === navFor);
    });
    document.body.classList.toggle('assets-page', state.view !== 'list' && state.view !== 'post');
    if (state.view === 'post') {
      renderPost(state.id);
    } else if (state.view === 'assets') {
      renderAssets();
    } else if (state.view === 'privacy') {
      renderPrivacy();
    } else if (state.view === '404') {
      render404();
    } else {
      els.search.value = state.q;
      els.tag.value = state.tag;
      els.images.value = state.images;
      els.sort.value = state.sort;
      document.title = 'GARDEN';
      renderList(state);
    }
    window.scrollTo(0, 0);
  }

  /* ----------------------------------------------------------- content tree */

  const TAG_COLORS = [
    '#96a8ff', '#f43b52', '#3ddc5a', '#ffae00', '#e879f9',
    '#22d3ee', '#fb923c', '#a3e635', '#f472b6', '#34d399',
  ];

  function tagColorMap() {
    const tags = [...new Set(posts.flatMap((p) => p.tags))].sort();
    const map = {};
    tags.forEach((t, i) => { map[t] = TAG_COLORS[i % TAG_COLORS.length]; });
    return map;
  }

  /* Groups posts under their primary (first) tag; every tag→post
     relationship is also drawn as a colored line, so posts with several
     tags visibly connect across groups. */
  function openTree() {
    const colors = tagColorMap();
    const groups = new Map();
    for (const p of postOrder()) {
      const primary = p.tags[0] || 'untagged';
      if (!groups.has(primary)) groups.set(primary, []);
      groups.get(primary).push(p);
    }

    const groupHtml = [...groups.entries()].map(([tag, list]) => `
      <div class="tree-group">
        <div class="tree-tag" data-tree-tag="${escapeHtml(tag)}">
          <span class="tree-dot" style="background:${colors[tag] || 'var(--text-3)'}"></span>#${escapeHtml(tag)}
        </div>
        <div class="tree-posts">
          ${list.map((p) => `
            <a class="tree-post" data-tree-post="${escapeHtml(p.id)}" href="#/post/${encodeURIComponent(p.id)}">
              ${escapeHtml(p.title)}
            </a>`).join('')}
        </div>
      </div>`).join('');

    els.treeBody.innerHTML = `
      <div class="tree-graph" id="tree-graph">
        <svg class="tree-lines" id="tree-lines" aria-hidden="true"></svg>
        ${groupHtml}
      </div>`;

    els.treeModal.hidden = false;
    document.body.style.overflow = 'hidden';
    drawTreeLines();
  }

  function drawTreeLines() {
    const graph = document.getElementById('tree-graph');
    const svg = document.getElementById('tree-lines');
    if (!graph || !svg) return;
    const colors = tagColorMap();
    const graphRect = graph.getBoundingClientRect();

    const rel = (r) => ({
      x: r.left - graphRect.left,
      y: r.top - graphRect.top,
      w: r.width,
      h: r.height,
    });

    const tagAnchors = {};
    graph.querySelectorAll('[data-tree-tag]').forEach((el) => {
      const r = rel(el.getBoundingClientRect());
      tagAnchors[el.getAttribute('data-tree-tag')] = { x: r.x + r.w, y: r.y + r.h / 2 };
    });

    const lines = [];
    graph.querySelectorAll('[data-tree-post]').forEach((el) => {
      const id = el.getAttribute('data-tree-post');
      const post = posts.find((p) => p.id === id);
      if (!post) return;
      const r = rel(el.getBoundingClientRect());
      const to = { x: r.x, y: r.y + r.h / 2 };
      for (const tag of (post.tags.length ? post.tags : ['untagged'])) {
        const from = tagAnchors[tag];
        if (!from) continue;
        const bend = Math.max(24, Math.abs(to.y - from.y) / 4);
        lines.push(`<path d="M ${from.x} ${from.y} C ${from.x + bend} ${from.y}, ${to.x - bend} ${to.y}, ${to.x} ${to.y}"
          stroke="${colors[tag] || '#5f9e6d'}" stroke-width="1.5" fill="none" opacity="0.75"/>`);
      }
    });

    svg.setAttribute('width', graph.scrollWidth);
    svg.setAttribute('height', graph.scrollHeight);
    svg.setAttribute('viewBox', `0 0 ${graph.scrollWidth} ${graph.scrollHeight}`);
    svg.innerHTML = lines.join('');
  }

  function closeTree() {
    if (els.treeModal.hidden) return;
    els.treeModal.hidden = true;
    document.body.style.overflow = '';
  }

  /* ------------------------------------------------------------- lightbox */

  function openLightbox(index) {
    if (!lightboxImages.length) return;
    lightboxIndex = index;
    updateLightbox();
    els.lightbox.hidden = false;
    document.body.style.overflow = 'hidden';
  }

  function updateLightbox() {
    const src = lightboxImages[lightboxIndex];
    els.lbImg.src = src;
    els.lbDownload.href = src;
    els.lbCounter.textContent = `${lightboxIndex + 1} / ${lightboxImages.length}`;
    els.lbPrev.disabled = lightboxIndex === 0;
    els.lbNext.disabled = lightboxIndex === lightboxImages.length - 1;
  }

  function closeLightbox() {
    if (els.lightbox.hidden) return;
    els.lightbox.hidden = true;
    els.lbImg.src = '';
    document.body.style.overflow = '';
  }

  /* --------------------------------------------------------------- events */

  els.search.addEventListener('input', writeListHash);
  els.tag.addEventListener('change', writeListHash);
  els.images.addEventListener('change', writeListHash);
  els.sort.addEventListener('change', writeListHash);

  window.addEventListener('hashchange', renderRoute);

  app.addEventListener('click', (e) => {
    const copyText = e.target.closest('[data-copy-text]');
    if (copyText) {
      navigator.clipboard.writeText(copyText.getAttribute('data-copy-text'));
      copyText.textContent = 'Copied';
      setTimeout(() => { copyText.textContent = 'Copy'; }, 1500);
      return;
    }
    const copyImgBtn = e.target.closest('[data-copy-img]');
    if (copyImgBtn) {
      copyImage(copyImgBtn.getAttribute('data-copy-img'), copyImgBtn);
      return;
    }
    const zipBtn = e.target.closest('[data-zip]');
    if (zipBtn) {
      downloadAllZip(zipBtn);
      return;
    }
    const layoutBtn = e.target.closest('[data-layout]');
    if (layoutBtn) {
      try { localStorage.setItem('garden-layout', layoutBtn.getAttribute('data-layout')); } catch {}
      renderRoute();
      return;
    }
    const treeBtn = e.target.closest('[data-tree]');
    if (treeBtn) {
      openTree();
      return;
    }
    const copyBlock = e.target.closest('[data-copy]');
    if (copyBlock) {
      navigator.clipboard.writeText(copyBlock.parentElement.querySelector('pre').textContent);
      copyBlock.textContent = 'Copied';
      setTimeout(() => { copyBlock.textContent = 'Copy'; }, 1500);
      return;
    }
    const tag = e.target.closest('[data-tag]');
    if (tag) {
      e.stopPropagation();
      els.tag.value = tag.getAttribute('data-tag');
      location.hash = '#/';
      writeListHash();
      return;
    }
    const lbImg = e.target.closest('[data-lightbox]');
    if (lbImg) {
      openLightbox(Number(lbImg.getAttribute('data-lightbox')));
      return;
    }
    const card = e.target.closest('[data-post]');
    if (card && !e.target.closest('a')) {
      location.hash = `#/post/${encodeURIComponent(card.getAttribute('data-post'))}`;
    }
  });

  app.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') {
      const card = e.target.closest('[data-post]');
      if (card) location.hash = `#/post/${encodeURIComponent(card.getAttribute('data-post'))}`;
    }
  });

  els.treeClose.addEventListener('click', closeTree);
  els.treeModal.addEventListener('click', (e) => {
    if (e.target === els.treeModal) closeTree();
    if (e.target.closest('.tree-post')) closeTree();
  });
  window.addEventListener('resize', () => { if (!els.treeModal.hidden) drawTreeLines(); });

  els.lbClose.addEventListener('click', closeLightbox);
  document.getElementById('lb-copy').addEventListener('click', (e) => {
    copyImage(lightboxImages[lightboxIndex], e.target);
  });
  els.lbPrev.addEventListener('click', () => { if (lightboxIndex > 0) { lightboxIndex--; updateLightbox(); } });
  els.lbNext.addEventListener('click', () => { if (lightboxIndex < lightboxImages.length - 1) { lightboxIndex++; updateLightbox(); } });
  els.lightbox.addEventListener('click', (e) => { if (e.target === els.lightbox) closeLightbox(); });

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && els.lightbox.hidden) { closeTree(); return; }
    if (els.lightbox.hidden) return;
    if (e.key === 'Escape') closeLightbox();
    if (e.key === 'ArrowLeft' && lightboxIndex > 0) { lightboxIndex--; updateLightbox(); }
    if (e.key === 'ArrowRight' && lightboxIndex < lightboxImages.length - 1) { lightboxIndex++; updateLightbox(); }
  });

  /* ----------------------------------------------------------------- init */

  async function init() {
    try {
      const [manifestRes, potdRes] = await Promise.all([
        fetch('content/manifest.json'),
        fetch('content/prompt-of-day.json'),
      ]);
      if (!manifestRes.ok) throw new Error(`manifest.json: HTTP ${manifestRes.status}`);
      const manifest = await manifestRes.json();
      posts = manifest.posts || [];
      assets = manifest.assets || [];
      assetDims = manifest.assetDims || {};

      if (potdRes.ok) {
        const potd = await potdRes.json();
        promptOfDay = pickPromptOfDay(potd.prompts || potd);
      }

      const tags = [...new Set(posts.flatMap((p) => p.tags))].sort();
      for (const t of tags) {
        const opt = document.createElement('option');
        opt.value = t;
        opt.textContent = `#${t}`;
        els.tag.appendChild(opt);
      }

      renderRoute();
    } catch (err) {
      app.innerHTML = `<div class="status">Failed to load content: ${escapeHtml(err.message)}.<br>
        Run <code>npm run build</code> to generate <code>content/manifest.json</code>.</div>`;
    }
  }

  init();
})();
